### ISSUE TITLE
How to manage kubeflow installation? 

### ISSUE THREAD

**Issue by mehdiasefi** [spotify/terraform-gke-kubeflow-cluster#6]
This module seems to be focusing on spin up and deploy k8 cluster. 
How do we manage kubeflow installation, or version upgrade using this module ? I do not see any notion of kubeflow release in this codebase.

**Comment by mattnworb** [comment]
We are not managing the Kubeflow installation itself via Terraform, just the setup of the GCP resources used by Kubeflow.

At Spotify we are still trying to figure out the best way to manage the customizations we want to make on top of the `kfctl`-generated manifests, see https://groups.google.com/d/msg/kubeflow-discuss/qH56Yoz4SoE/Urrn5YRIEQAJ for some discussion and pointers.

Regarding upgrades, since 0.7 there is alpha support for in-place upgrades: https://www.kubeflow.org/docs/upgrading/upgrade/#upgrading-from-kubeflow-v0-7-0-or-later.
